# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:11.9.0-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule update -i
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - run: npm run test

  uploadPreview:
    docker:
      - image: circleci/node:11.9.0-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule update -i
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run uploadPreview

  deploy:
    docker:
      - image: circleci/node:11.9.0-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule update -i
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: npm run deploy
          command: |
            git config --global user.email "yikeura@microsoft.com"
            git config --global user.name "yikeura700"
            npm run deploy
      - run: npm run deleteMergedPreview
          


workflows:
    version: 2
    deploy:
      jobs:
        - test
        - uploadPreview:
            requires:
              - test
            filters:
              branches:
                ignore: master
        - deploy:
            requires:
                - test
            filters:
              branches:
                only: master

